
version: '3.8'
services:
  pacificCampsiteAPI-postgresql:
    image: postgres:14.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pacificCampsiteApiDB
    ports:
      - 127.0.0.1:5432:5432
